name: Build and Push Binaries to S3

on:
  workflow_call:
    inputs:
      dockerfile_path:
        description: 'The path to the Dockerfile'
        required: true
        type: string
      aws_s3_bucket_folder:
        description: 'The name of AWS S3 bucket folder to upload binaries to'
        required: false
        type: string
      coin_repo_owner:
        description: 'github repo owner'
        required: true
        type: string
      coin_repo_name:
        description: 'github repo name'
        required: true
        type: string
      version:
        description: 'Version to build (leave empty for latest)'
        required: false
        type: string

env:
  docker_image: "temp_image:latest"

jobs:
  build-and-upload:
    runs-on: [self-hosted, Linux, ARM64]
    steps:
      - name: Get latest tag
        id: latest_tag
        if: inputs.version == ''
        shell: bash
        run: |
          echo "version=$(curl -sLX GET "https://api.github.com/repos/${{ inputs.coin_repo_owner }}/${{ inputs.coin_repo_name }}/releases/latest" | jq --raw-output '.tag_name')" >> $GITHUB_OUTPUT

      - name: Set version
        id: set_version
        run: |
          if [ -n "${{ inputs.version }}" ]; then
            echo "version=${{ inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "version=${{ steps.latest_tag.outputs.version }}" >> $GITHUB_OUTPUT
          fi

      - name: Build and push
        run: |
          # Your build and push logic here
          echo "Building version ${{ steps.set_version.outputs.version }}"